In [2]:
import numpy as np 
np.zeros(5) # 1d array of size 5 with zero default float  
np.zeros(5,dtype=int) # 1d array of size 5 with zero 
np.zeros((3,4)) # 1d array of size 5 with zero 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [16]:
# 3d array
brr=np.zeros((3,4,5))


In [20]:
brr+5# add 5 to eachele  

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [24]:
arr=np.zeros((3,4))+5
arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
arr*2 #multi[ly each ele by 2  

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [30]:
arr -2 # subtract 2 from each element

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [32]:
arr/5 #divide elements by 5 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.eye(3) # 3X3 array all diagonal elements 1 rest are 0 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
arr=np.empty((3,4)) # random elements

In [44]:
import random
random.choice((1,2,3,4))
random.randrange(1,10)

4

In [46]:
random.random() # random included 0 to 1 1 is not included 0 is included

0.4146853530943767

In [48]:
l=[1,2,3,4,5]
random.shuffle(l)

In [50]:
l

[4, 3, 5, 2, 1]

In [52]:
random.uniform(7,14) # gives uniform distribution

11.780990570549914

In [54]:
# random in mumpy 
np.array([])
np.random.random_sample((5)) # array of 5 random numbers

array([0.13561066, 0.26230659, 0.38398603, 0.80932223, 0.10783891])

In [58]:
np.random.rand(3) # 1 d array 

array([0.79393938, 0.22300284, 0.96866037])

In [60]:
np.random.randn(4)

array([-1.09860767,  0.56605755,  1.27529249, -2.09659465])

In [64]:
arr=np.random.randint(1,5,size=(3,4)) # 5 is excluded

array([[3, 4, 3, 1],
       [2, 3, 2, 3],
       [4, 3, 3, 1]])

In [70]:
arr.ndim
arr.size

12