In [1]:
import numpy as np

In [3]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [5]:
arr1.flatten() # Return a copy of the array collapsed into one dimension.


array([2, 2, 1, 2, 2, 1, 1, 1, 1])

In [7]:
# expand dimension
arr=np.array([1,2,3,4,5])
np.expand_dims(arr,axis=0) # increase the deimension by 1 >> 0 means row wise 1 means col wise 

array([[1, 2, 3, 4, 5]])

In [9]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
arr=np.zeros((3,4))
np.expand_dims(arr,axis=0) 
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [25]:
a=np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [13]:

np.squeeze(a)# remove 1 dimension

array([1, 2, 3])

In [27]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [31]:
np.repeat(a,4,axis=0)

array([[1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3]])

In [33]:
np.repeat(a,4,axis=1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [37]:
np.roll(a,-1) # shift 1 place

array([[2],
       [3],
       [1]])

In [39]:
np.roll(a,1) # shift 1 place

array([[3],
       [1],
       [2]])

In [41]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [45]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])