In [2]:
import numpy as np 
np.zeros(5) # 1d array of size 5 with zero default float  
np.zeros(5,dtype=int) # 1d array of size 5 with zero 
np.zeros((3,4)) # 1d array of size 5 with zero 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [16]:
# 3d array
brr=np.zeros((3,4,5))


In [20]:
brr+5# add 5 to eachele  

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [24]:
arr=np.zeros((3,4))+5
arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
arr*2 #multi[ly each ele by 2  

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [30]:
arr -2 # subtract 2 from each element

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [32]:
arr/5 #divide elements by 5 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.eye(3) # 3X3 array all diagonal elements 1 rest are 0 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
arr=np.empty((3,4)) # random elements

In [44]:
import random
random.choice((1,2,3,4))
random.randrange(1,10)

4

In [46]:
random.random() # random included 0 to 1 1 is not included 0 is included

0.4146853530943767

In [48]:
l=[1,2,3,4,5]
random.shuffle(l)

In [50]:
l

[4, 3, 5, 2, 1]

In [52]:
random.uniform(7,14) # gives uniform distribution

11.780990570549914

In [54]:
# random in mumpy 
np.array([])
np.random.random_sample((5)) # array of 5 random numbers

array([0.13561066, 0.26230659, 0.38398603, 0.80932223, 0.10783891])

In [58]:
np.random.rand(3) # 1 d array 

array([0.79393938, 0.22300284, 0.96866037])

In [60]:
np.random.randn(4)

array([-1.09860767,  0.56605755,  1.27529249, -2.09659465])

In [86]:
arr=np.random.randint(1,5,size=(3,4)) # 5 is excluded

In [88]:
arr.ndim
arr.size
arr

array([[2, 1, 3, 4],
       [4, 3, 2, 3],
       [3, 1, 3, 2]])

In [90]:
# reshaping of array 
arr.reshape(2,6) # size must be same 


array([[2, 1, 3, 4, 4, 3],
       [2, 3, 3, 1, 3, 2]])

In [92]:
arr.reshape(4,-1) # use any negative value if no. col/row is not sure 
arr

array([[2, 1, 3, 4],
       [4, 3, 2, 3],
       [3, 1, 3, 2]])

In [94]:
arr.reshape(12,1).base # to see original array

array([[2, 1, 3, 4],
       [4, 3, 2, 3],
       [3, 1, 3, 2]])

In [96]:
arr.reshape(2,2,3)

array([[[2, 1, 3],
        [4, 4, 3]],

       [[2, 3, 3],
        [1, 3, 2]]])

In [98]:
arr.reshape(1,2,2,3)

array([[[[2, 1, 3],
         [4, 4, 3]],

        [[2, 3, 3],
         [1, 3, 2]]]])

In [102]:
# conditions on array
arr=np.random.randint(1,10,size=(5,6))

In [104]:
arr>3 # true if elements if value is >3

array([[False,  True,  True, False, False,  True],
       [ True,  True,  True, False,  True, False],
       [ True, False, False,  True,  True, False],
       [ True,  True,  True,  True, False, False],
       [ True, False,  True,  True, False,  True]])

In [106]:
arr[arr>3] # select all the elements of array where condition is true

array([8, 4, 8, 8, 5, 4, 9, 4, 6, 8, 4, 6, 8, 5, 9, 5, 7, 6])

In [108]:
# to access elements 
arr[0]

array([3, 8, 4, 3, 1, 8])

In [110]:
arr[0][1]

8

In [112]:
arr[0:3]

array([[3, 8, 4, 3, 1, 8],
       [8, 5, 4, 3, 9, 2],
       [4, 1, 2, 6, 8, 3]])

In [114]:
arr[1:2]

array([[8, 5, 4, 3, 9, 2]])

In [116]:
arr[0:3,[0,2]]

array([[3, 4],
       [8, 4],
       [4, 2]])

In [120]:
# slicing array
arr[0:3,0:2]

array([[3, 8],
       [8, 5],
       [4, 1]])

In [122]:
arr1=arr[0:3,0:2]
arr1

array([[3, 8],
       [8, 5],
       [4, 1]])

In [126]:
# mathematical operation on 2 array
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [128]:
arr1+arr2 # index wise addition

array([[10,  8, 12],
       [10, 13,  3],
       [12,  9, 15]])

In [130]:
arr1*arr2 # index wise multiplication not a matrix multiplication

array([[16, 15, 36],
       [16, 40,  2],
       [35, 20, 56]])

In [136]:
arr1/arr2

array([[4.        , 1.66666667, 1.        ],
       [4.        , 0.625     , 0.5       ],
       [0.71428571, 1.25      , 0.875     ]])

## 

In [141]:
arr1 -arr2

array([[ 6,  2,  0],
       [ 6, -3, -1],
       [-2,  1, -1]])

In [143]:
arr1/0 # gives oinfinity with warning

C:\Users\hp\AppData\Local\Temp\ipykernel_30360\2734841744.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # gives oinfinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [147]:
# matrix multiplication
arr1 @arr2
# or
np.dot(arr1,arr2)

array([[ 68,  88, 106],
       [ 33,  68,  66],
       [ 69,  83,  96]])

In [149]:
# broadcasting
arr=np.zeros((3,4))

In [ ]:
arr+5