In [2]:
import numpy as np 
np.zeros(5) # 1d array of size 5 with zero default float  
np.zeros(5,dtype=int) # 1d array of size 5 with zero 
np.zeros((3,4)) # 1d array of size 5 with zero 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [16]:
# 3d array
brr=np.zeros((3,4,5))


In [18]:
brr+5# add 5 to 

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])