In [1]:
import numpy as np

In [3]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [5]:
arr1.flatten() # Return a copy of the array collapsed into one dimension.


array([2, 2, 1, 2, 2, 1, 1, 1, 1])

In [7]:
# expand dimension
arr=np.array([1,2,3,4,5])
np.expand_dims(arr,axis=0) # increase the deimension by 1 >> 0 means row wise 1 means col wise 

array([[1, 2, 3, 4, 5]])

In [9]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
arr=np.zeros((3,4))
np.expand_dims(arr,axis=0) 
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [25]:
a=np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [13]:

np.squeeze(a)# remove 1 dimension

array([1, 2, 3])

In [27]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [31]:
np.repeat(a,4,axis=0)

array([[1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3]])

In [33]:
np.repeat(a,4,axis=1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [37]:
np.roll(a,-1) # shift 1 place

array([[2],
       [3],
       [1]])

In [39]:
np.roll(a,1) # shift 1 place

array([[3],
       [1],
       [2]])

In [41]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [45]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [53]:
-arr1

array([[-2, -2, -1],
       [-2, -2, -1],
       [-1, -1, -1]])

In [55]:
# operation on numpy atrings array
d=np.array(["pw","skills"])

In [57]:
np.char.upper(d) 

array(['PW', 'SKILLS'], dtype='<U6')

In [59]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [63]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [67]:
np.cos(arr1)


array([[-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231]])

In [77]:
np.log10(arr1)


array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

### 

In [80]:
np.power(arr1,3)

array([[8, 8, 1],
       [8, 8, 1],
       [1, 1, 1]], dtype=int32)

In [84]:
np.max(arr1)


2

In [86]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [88]:
np.mean(arr1)

1.4444444444444444

In [90]:
np.std(arr1)

0.4969039949999533

In [92]:
np.var(arr1)

0.2469135802469136

In [96]:
np.subtract(arr1,arr2)

array([[ 1,  0, -1],
       [ 1,  0,  0],
       [-1,  0, -1]])

In [98]:
np.multiply(arr1,arr2)

array([[2, 4, 2],
       [2, 4, 1],
       [2, 1, 2]])

In [100]:
np.mod(arr1,arr2)

array([[0, 0, 1],
       [0, 0, 0],
       [1, 0, 1]])

In [102]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [104]:
# sorting and swarching


In [106]:
np.sort(arr1)

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [112]:
e=np.array([2,4,64,0,0,2345,645])

In [110]:
np.searchsorted(e,32) # give index 

2

In [114]:
np.count_nonzero(e)

5

In [116]:
np.where(e>0)

(array([0, 1, 2, 5, 6], dtype=int64),)

In [118]:
np.extract(e>0,e)

array([   2,    4,   64, 2345,  645])

In [120]:
e.byteswap()

array([   33554432,    67108864,  1073741824,           0,           0,
         688455680, -2063466496])

In [122]:
import numpy.matlib as nm

In [124]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [126]:
# numpy linear algebra


In [128]:
np.linalg.det(arr1)

0.0

In [130]:
# inverse 

In [132]:
np.linalg.inv(arr2)

array([[-1.        ,  0.66666667,  0.66666667],
       [ 0.        ,  0.66666667, -0.33333333],
       [ 1.        , -1.        ,  0.        ]])

In [136]:
# solving equation using numpy array
a=np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])
b=np.array([16,8,,3,2])