In [1]:
# numpy>> umerical python developed in 2005 by travis oliphant
import numpy as np # as>>alias



In [5]:
np.__version__

'1.26.4'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [11]:
# numpy stroes data in numpy array
# stroes homogenous data
## why numpy ?
'''
built using c computation is fast
fast due to array stores only homogenous data 
continous memory allocation

'''

'\nbuilt using c computation is fast\nfast due to array stores only homogenous data \ncontinous memory allocation\n\n'

In [19]:
# array stores homogenous data
l=[1,2,3,4]
arr=np.array(l)
l=[1,2,"a",3]
arr=np.array(l) # all members became string ['1', '2', 'a', '3']
arr


array(['1', '2', 'a', '3'], dtype='<U11')

In [21]:
arr.ndim # give dimension of array

1

In [27]:
arr=np.array([[1,2,3,4],[1,5,7,8]])

In [29]:
arr.ndim #2

2

In [35]:
mat=np.matrix([1,2,3,4])   # always be 2 dimensoin
mat #matrix([[1, 2, 3, 4]])


matrix([[1, 2, 3, 4]])

In [37]:
l=[1,2,3]
np.asarray(l)    # inital function /older approach
np.asanyarray(l) # not convert arr to array
np.asanyarray(mat) # it will simply allow to pass threw it ,it will remain as matrix 

matrix([[1, 2, 3, 4]])

In [39]:
# tuple as array
t=([1,2,3])
np.array(t)

array([1, 2, 3])

In [51]:
arr=np.array([1,2,34])
arr[0]

1

In [53]:
# array is mutable
arr[0]=100
arr[0]

100

In [55]:
a=arr # shallow copy >>point to same memory location changes will reflect on both
a[0]=3
arr[0] # 3 

3

In [59]:
# deep copy >> chnages in one array will not reflect in another
a=arr.copy()
a[0]=5
arr[0] # 3 

3

In [67]:
arr=np.fromfunction(lambda i,j :i==j ,(3,3) )
'''array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])'''

'array([[ True, False, False],\n       [False,  True, False],\n       [False, False,  True]])'

In [69]:
arr.ndim

2

In [71]:
arr.shape

(3, 3)

In [73]:
arr.size # no. of elements

9

In [75]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [83]:
arr=np.fromiter((i for i in range(5)),int)
arr

array([0, 1, 2, 3, 4])

In [93]:
np.fromstring(" 1 2 3 4",sep=" ")
np.fromstring(" 1 2 3 4",sep=" ",dtype=int) # value inside string should be numerical


C:\Users\hp\AppData\Local\Temp\ipykernel_44028\3930417972.py:3: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring(" 1 2 asdf 4",sep=" ",dtype=int) # value inside string should be numerical


array([1, 2])

In [97]:
np.arange(1,10) #array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(1,10,4) #array([1, 5, 9])

array([1, 5, 9])

In [99]:
np.linspace(1,5,10) #array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])